import {validatePost} from './core.mjs';
export class Publisher {
 constructor(token,request=fetch){this.token=token;this.request=request;this.owner='NobodysSimple';this.repo='nobodyssimple';this.branch='main';}
 async api(path,method='GET',body){const response=await this.request(`https://api.github.com${path}`,{method,headers:{Authorization:`Bearer ${this.token}`,Accept:'application/vnd.github+json','Content-Type':'application/json','X-GitHub-Api-Version':'2022-11-28'},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok){if(response.status===401)throw Error('GitHub could not authenticate this token. Check whether it has expired.');if(response.status===403||response.status===404)throw Error('GitHub denied access. Check that the token can access NobodysSimple/nobodyssimple and has Contents: Read and write.');if(response.status===409||response.status===422)throw Error('The repository changed, or a branch rule prevented publishing. Reload the studio and try again. Your draft is still here.');throw Error(`GitHub could not complete this operation (${response.status}). Your draft is still here.`);}return response.status===204?null:response.json();}
 get base(){return `/repos/${this.owner}/${this.repo}`;}
 async connect(){const user=await this.api('/user');if(user.login.toLowerCase()!==this.owner.toLowerCase())throw Error('Sign in with the NobodysSimple owner account.');const repo=await this.api(this.base);if(!repo.permissions?.push)throw Error('This account does not have permission to publish to this repository.');await this.api(`${this.base}/git/ref/heads/${this.branch}`);return user;}
 async snapshot(){const ref=await this.api(`${this.base}/git/ref/heads/${this.branch}`);const head=ref.object.sha;const commit=await this.api(`${this.base}/git/commits/${head}`);const file=await this.api(`${this.base}/contents/content.json?ref=${head}`);const data=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(file.content.replace(/\s/g,'')),c=>c.charCodeAt(0))));if(!Array.isArray(data.posts))throw Error('The content index is not in the expected format.');return {head,tree:commit.tree.sha,data};}
 async publish(post,images=[],previous=null){validatePost(post);const snapshot=await this.snapshot();const existing=snapshot.data.posts.find(p=>p.id===post.id);if(existing&&(!previous||JSON.stringify(existing)!==JSON.stringify(previous)))throw Error('This piece has changed since you opened it. Download your draft, reload the studio, and open the latest version before publishing.');if(previous&&!existing)throw Error('This piece has been removed since you opened it. Reload before publishing.');const tree=[];
 for(const image of images){if(!/^media\/[a-zA-Z0-9_.-]+\.(png|jpg|jpeg|webp)$/.test(image.path))throw Error('Unsupported image path.');const blob=await this.api(`${this.base}/git/blobs`,'POST',{content:image.base64,encoding:'base64'});tree.push({path:image.path,mode:'100644',type:'blob',sha:blob.sha});}
 const next={...snapshot.data,posts:[post,...snapshot.data.posts.filter(p=>p.id!==post.id)]};tree.push({path:'content.json',mode:'100644',type:'blob',content:JSON.stringify(next,null,2)+'\n'});const newTree=await this.api(`${this.base}/git/trees`,'POST',{base_tree:snapshot.tree,tree});const commit=await this.api(`${this.base}/git/commits`,'POST',{message:`${post.status==='published'?'Publish':'Unpublish'}: ${post.title}`,tree:newTree.sha,parents:[snapshot.head]});await this.api(`${this.base}/git/refs/heads/${this.branch}`,'PATCH',{sha:commit.sha,force:false});return {sha:commit.sha,data:next};}
 disconnect(){this.token='';}
}
