import { escapeHTML as esc } from "./core.mjs";

const key = "ns-sensory-recipes-v2";
const states = ["Too much input", "Too little input", "Restless", "Flat / shut down", "Social overload", "Transition stress", "Trying to focus", "Trying to sleep", "Crowded place", "Noisy place", "Unexpected change", "Headache / body overload", "Not sure"];
const ingredients = ["quieter", "dimmer", "headphones", "movement", "deep pressure", "familiar sound", "familiar object", "less talking", "more space", "company", "being alone", "fresh air", "cold drink", "snack", "predictable routine", "leaving the room", "changing clothes", "lower screen brightness", "sunglasses", "hood or hat", "fidget", "weighted blanket", "earplugs", "change seat", "written information", "transition warning", "something else"];
const earlySigns = ["sounds feel sharper", "lights feel harsher", "I stop following conversation", "I become irritable", "I want to escape", "I go quiet", "I start pacing", "my body feels tense", "I cannot think", "I stop noticing hunger or thirst", "I feel numb", "I become more emotional", "not sure yet"];
const contexts = ["at home", "at work", "at university / school", "in public", "during travel", "when tired", "when stressed", "when alone", "when with people", "only if I can leave", "only if I choose it", "depends"];
const backfires = ["makes me more restless", "makes me more overloaded", "makes me sleepy", "makes me irritable", "makes me feel trapped", "works only briefly", "makes body sensations stronger", "too effortful", "not available", "helps sometimes but not others"];
const backups = ["move farther away", "use earplugs", "face away from the input", "step outside", "reduce another input", "change seat", "use a familiar object", "ask for written information", "pause the conversation", "nothing available right now"];
const resultOptions = ["Much better", "A little better", "No change", "Worse", "Not sure"];
const empty = () => ({ state: "Too much input", early: [], columns: { best: [], sometimes: [], depends: [], avoid: [] }, meta: {}, reset: { thirty: "", five: "", thirtyMin: "" }, result: "", resultNote: "" });
const load = () => { try { const saved = JSON.parse(localStorage.getItem(key) || "null"); return saved ? { ...empty(), ...saved, columns: { ...empty().columns, ...(saved.columns || {}) }, meta: saved.meta || {} } : empty(); } catch { return empty(); } };
const save = (recipe) => localStorage.setItem(key, JSON.stringify(recipe));
const toggle = (array, value) => { const index = array.indexOf(value); if (index >= 0) array.splice(index, 1); else array.push(value); };
const download = (name, text) => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); };
const textFor = (recipe) => `My sensory recipe: ${recipe.state}\n\nUse when: ${recipe.early.join(", ") || "Not selected"}\n\nFirst choice: ${recipe.columns.best.join(", ") || "Not selected"}\nSometimes: ${recipe.columns.sometimes.join(", ") || "Not selected"}\nDepends: ${recipe.columns.depends.join(", ") || "Not selected"}\nAvoid / backfires: ${recipe.columns.avoid.join(", ") || "Not selected"}\n\n30 seconds: ${recipe.reset.thirty || "Not set"}\n5 minutes: ${recipe.reset.five || "Not set"}\n30 minutes: ${recipe.reset.thirtyMin || "Not set"}\n\nTest result: ${recipe.result || "Not recorded"}\nWhat I noticed: ${recipe.resultNote || "None"}`;

export function renderSensoryRecipe(root, tool) {
  const state = { page: "build", selected: null };
  let recipe = load();
  const attr = (value) => esc(String(value)).replace(/"/g, "&quot;");
  const hasItem = (item) => Object.values(recipe.columns).some((items) => items.includes(item));
  const chips = (items, values, type) => items.map((item) => `<button type="button" class="recipe-chip ${values.includes(item) ? "selected" : ""}" data-recipe-toggle="${type}" data-recipe-value="${attr(item)}">${esc(item)}</button>`).join("");
  const detail = () => {
    if (!state.selected) return `<p class="recipe-select-hint">Select an ingredient above to record how well it works in real life.</p>`;
    const item = state.selected;
    const meta = recipe.meta[item] || (recipe.meta[item] = { usefulness: "", speed: "", ease: "", discreet: "", contexts: [], unavailable: false, backup: "", backfires: [] });
    const option = (value, selected) => `<option ${selected === value ? "selected" : ""}>${value}</option>`;
    return `<section class="recipe-detail"><div class="recipe-step-head"><span>Refine this ingredient</span><strong>${esc(item)}</strong></div><div class="recipe-detail-grid"><label class="field">How well does it help?<select data-recipe-meta="usefulness"><option value="">Choose one</option>${["Sometimes useful", "Reliable", "Very helpful"].map((v) => option(v, meta.usefulness)).join("")}</select></label><label class="field">How quickly does it help?<select data-recipe-meta="speed"><option value="">Choose one</option>${["Almost immediately", "Within a few minutes", "Only after a while", "Not sure"].map((v) => option(v, meta.speed)).join("")}</select></label><label class="field">How easy is it to do?<select data-recipe-meta="ease"><option value="">Choose one</option>${["Very easy", "Possible", "Difficult", "Usually unavailable"].map((v) => option(v, meta.ease)).join("")}</select></label><label class="field">Can you do it discreetly?<select data-recipe-meta="discreet"><option value="">Choose one</option>${["Discreet", "Somewhat noticeable", "Obvious", "Only in private"].map((v) => option(v, meta.discreet)).join("")}</select></label></div><h4>When does this help?</h4><div class="recipe-chip-grid">${chips(contexts, meta.contexts, "meta-context")}</div><label class="recipe-check"><input type="checkbox" data-recipe-unavailable ${meta.unavailable ? "checked" : ""}> Helpful, but often unavailable</label><label class="field">If it is unavailable, what is the backup?<select data-recipe-backup><option value="">Choose one</option>${backups.map((v) => option(v, meta.backup)).join("")}</select></label><h4>What tends to go wrong?</h4><div class="recipe-chip-grid">${chips(backfires, meta.backfires, "meta-backfire")}</div></section>`;
  };
  const columns = () => { const make = (id, title, hint) => `<section class="recipe-column recipe-${id}"><div><h3>${title}</h3><p>${hint}</p></div><div class="recipe-column-items">${recipe.columns[id].length ? recipe.columns[id].map((item) => `<button type="button" class="recipe-item" data-recipe-item="${attr(item)}">${esc(item)}<small>Tap to edit</small></button>`).join("") : `<span class="recipe-empty">Tap an ingredient to place it here.</span>`}</div></section>`; return make("best", "First choice", "Try this first when it is available.") + make("sometimes", "Sometimes useful", "Helpful in some conditions or for a short time.") + make("depends", "Depends", "Useful only with the right context, control or timing.") + make("avoid", "Avoid / backfires", "What tends to make this moment harder."); };
  const timePlan = () => `<section class="recipe-time-plan"><div class="recipe-step-head"><span>4 / Minimum viable reset</span><strong>If you only have this much time</strong></div><div class="recipe-time-grid"><label class="field"><span>30 seconds</span><input data-recipe-reset="thirty" value="${attr(recipe.reset.thirty)}" placeholder="One tiny change"></label><label class="field"><span>5 minutes</span><input data-recipe-reset="five" value="${attr(recipe.reset.five)}" placeholder="A short reset"></label><label class="field"><span>30 minutes</span><input data-recipe-reset="thirtyMin" value="${attr(recipe.reset.thirtyMin)}" placeholder="A fuller recovery plan"></label></div></section>`;
  const build = () => `<div class="recipe-intro"><p class="eyebrow">Calm & sensory / Assemble, test, refine</p><h1>Build a sensory recipe you can actually use.</h1><p class="lead">${esc(tool.short)}</p><div class="recipe-purpose"><div><span>Use this when</span><strong>you notice a pattern starting and want a practical response</strong></div><div><span>The aim</span><strong>match the support to the moment, not find one perfect strategy</strong></div><div><span>Finish with</span><strong>a first choice, a backup and a minimum viable reset</strong></div></div></div><section class="recipe-workbench"><div class="recipe-step-head"><span>1 / Name the moment</span><strong>What kind of recipe are you making?</strong></div><div class="recipe-state-grid">${states.map((item) => `<button type="button" class="recipe-state ${recipe.state === item ? "selected" : ""}" data-recipe-state="${attr(item)}">${esc(item)}</button>`).join("")}</div><div class="recipe-step-head"><span>2 / Notice the signal</span><strong>What tells you the recipe may be needed?</strong></div><div class="recipe-chip-grid">${chips(earlySigns, recipe.early, "early")}</div><div class="recipe-step-head"><span>3 / Assemble the tray</span><strong>Tap an ingredient to move it through the recipe.</strong><small>Tap order: First choice → Sometimes → Depends → Avoid / backfires → First choice.</small></div><div class="recipe-ingredient-tray">${ingredients.map((item) => `<button type="button" class="recipe-ingredient ${hasItem(item) ? "placed" : ""}" data-recipe-ingredient="${attr(item)}">${esc(item)}</button>`).join("")}</div><div class="recipe-columns">${columns()}</div>${detail()}${timePlan()}<div class="recipe-actions"><button type="button" class="button" data-recipe-action="summary">Build my recipe card</button><button type="button" class="button secondary" data-recipe-action="clear">Start this recipe again</button></div></section>`;
  const summary = () => `<div class="recipe-intro"><p class="eyebrow">Your sensory recipe · ${esc(recipe.state)}</p><h1>A plan for when the pattern starts.</h1><p class="lead">Use the first-choice option if it is available. If not, move to the backup without treating the first option as a failure.</p></div><section class="recipe-card"><div class="recipe-card-title"><span>RECIPE</span><h2>${esc(recipe.state)}</h2><button type="button" class="chip" data-recipe-action="build">Edit recipe</button></div><div class="recipe-card-grid"><article><h3>Use the recipe when</h3><p>${esc(recipe.early.join(" · ") || "No early signs selected yet")}</p></article><article><h3>First choice</h3><p>${esc(recipe.columns.best.join(" · ") || "No first choice selected yet")}</p></article><article><h3>Backup / if unavailable</h3><p>${esc(Object.values(recipe.meta).map((meta) => meta.backup).filter(Boolean).join(" · ") || recipe.reset.five || "Add a backup in the builder")}</p></article><article><h3>Avoid / usually backfires</h3><p>${esc(recipe.columns.avoid.join(" · ") || "No avoid list selected")}</p></article><article><h3>30 seconds</h3><p>${esc(recipe.reset.thirty || "Not set yet")}</p></article><article><h3>5 minutes</h3><p>${esc(recipe.reset.five || "Not set yet")}</p></article><article><h3>30 minutes</h3><p>${esc(recipe.reset.thirtyMin || "Not set yet")}</p></article></div><section class="recipe-recheck"><h3>Test and re-check</h3><p>Try one ingredient when appropriate, then record what changed. This keeps the recipe evidence-based and revisable.</p><div class="recipe-chip-grid">${resultOptions.map((item) => `<button type="button" class="recipe-chip ${recipe.result === item ? "selected" : ""}" data-recipe-result="${attr(item)}">${esc(item)}</button>`).join("")}</div><label class="field">What did you notice?<textarea id="recipe-result-note" rows="3" placeholder="The strategy helped when..., but not when...">${esc(recipe.resultNote)}</textarea></label></section><div class="recipe-actions"><button type="button" class="button" data-recipe-action="save-map">Save to My Maps</button><button type="button" class="button secondary" data-recipe-action="download">Download recipe</button><button type="button" class="button secondary" data-recipe-action="copy">Copy recipe</button></div><p id="recipe-status" class="fine" role="status"></p></section>`;
  const render = () => { root.innerHTML = `<div class="wrap sensory-recipe-page">${state.page === "build" ? build() : summary()}</div>`; bind(); };
  const bind = () => {
    root.querySelectorAll("[data-recipe-state]").forEach((button) => button.addEventListener("click", () => { recipe.state = button.dataset.recipeState; save(recipe); render(); }));
    root.querySelectorAll("[data-recipe-ingredient]").forEach((button) => button.addEventListener("click", () => { const item = button.dataset.recipeIngredient; const columns = Object.entries(recipe.columns); const current = columns.find(([, values]) => values.includes(item)); const order = ["best", "sometimes", "depends", "avoid"]; if (!current) recipe.columns.best.push(item); else { current[1].splice(current[1].indexOf(item), 1); recipe.columns[order[(order.indexOf(current[0]) + 1) % order.length]].push(item); } state.selected = item; save(recipe); render(); }));
    root.querySelectorAll("[data-recipe-item]").forEach((button) => button.addEventListener("click", () => { state.selected = button.dataset.recipeItem; render(); }));
    root.querySelectorAll("[data-recipe-toggle]").forEach((button) => button.addEventListener("click", () => { const type = button.dataset.recipeToggle; if (type === "early") toggle(recipe.early, button.dataset.recipeValue); else { const meta = recipe.meta[state.selected] || (recipe.meta[state.selected] = { usefulness: "", speed: "", ease: "", discreet: "", contexts: [], unavailable: false, backup: "", backfires: [] }); toggle(type === "meta-context" ? meta.contexts : meta.backfires, button.dataset.recipeValue); } save(recipe); render(); }));
    root.querySelectorAll("[data-recipe-meta]").forEach((select) => select.addEventListener("change", () => { recipe.meta[state.selected][select.dataset.recipeMeta] = select.value; save(recipe); }));
    root.querySelector("[data-recipe-unavailable]")?.addEventListener("change", (event) => { recipe.meta[state.selected].unavailable = event.target.checked; save(recipe); });
    root.querySelector("[data-recipe-backup]")?.addEventListener("change", (event) => { recipe.meta[state.selected].backup = event.target.value; save(recipe); });
    root.querySelectorAll("[data-recipe-reset]").forEach((input) => input.addEventListener("input", () => { recipe.reset[input.dataset.recipeReset] = input.value; save(recipe); }));
    root.querySelectorAll("[data-recipe-result]").forEach((button) => button.addEventListener("click", () => { recipe.result = button.dataset.recipeResult; save(recipe); render(); }));
    root.querySelector("#recipe-result-note")?.addEventListener("input", (event) => { recipe.resultNote = event.target.value; save(recipe); });
    root.querySelectorAll("[data-recipe-action]").forEach((button) => button.addEventListener("click", () => { const action = button.dataset.recipeAction; if (action === "summary") { state.page = "summary"; render(); } else if (action === "build") { state.page = "build"; render(); } else if (action === "clear") { recipe = empty(); state.selected = null; save(recipe); render(); } else if (action === "save-map") { try { const maps = JSON.parse(localStorage.getItem("ns-personal-maps-v1") || "[]"); maps.unshift({ id: crypto.randomUUID(), title: `Sensory recipe · ${recipe.state}`, tool: "sensory-recipe", answers: recipe, savedAt: new Date().toISOString(), status: "New observation" }); localStorage.setItem("ns-personal-maps-v1", JSON.stringify(maps.slice(0, 250))); root.querySelector("#recipe-status").textContent = "Saved on this device."; } catch { root.querySelector("#recipe-status").textContent = "This browser could not save the recipe."; } } else if (action === "download") download("sensory-recipe.txt", textFor(recipe)); else if (action === "copy") navigator.clipboard?.writeText(textFor(recipe)).then(() => { root.querySelector("#recipe-status").textContent = "Copied."; }).catch(() => { root.querySelector("#recipe-status").textContent = "Copy was blocked by this browser. Use Download instead."; }); }));
  };
  render();
}
