import { escapeHTML as esc } from "./core.mjs";

const key = "ns-sensory-recipes-v3";
const situations = ["Too much input", "Too little input", "Restless", "Flat / shut down", "Social overload", "Transition stress", "Trying to focus", "Trying to sleep", "Not sure"];
const supports = ["Quieter", "Dimmer", "Headphones", "Earplugs", "More space", "Fresh air", "Movement", "Deep pressure", "Familiar sound", "Familiar object", "Less talking", "Company", "Being alone", "Cold drink", "Snack", "Change seat", "Leave the room", "Lower screen brightness", "Something else"];
const earlySigns = ["Sounds feel sharper", "Lights feel harsher", "I stop following conversation", "I become irritable", "I want to escape", "I go quiet", "I start pacing", "My body feels tense", "I cannot think", "I feel numb", "Not sure yet"];
const resultOptions = ["Better", "A little better", "No change", "Worse", "Not sure"];
const empty = () => ({ situation: "Too much input", first: "", backup: "", avoid: "", early: [], quick: "", longer: "", result: "", resultNote: "" });
const load = () => { try { const saved = JSON.parse(localStorage.getItem(key) || "null"); return saved ? { ...empty(), ...saved, early: Array.isArray(saved.early) ? saved.early : [] } : empty(); } catch { return empty(); } };
const save = (recipe) => localStorage.setItem(key, JSON.stringify(recipe));
const attr = (value) => esc(String(value)).replace(/"/g, "&quot;");
const toggle = (items, value) => { const index = items.indexOf(value); if (index >= 0) items.splice(index, 1); else items.push(value); };
const download = (name, text) => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/plain" })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); };
const recipeText = (recipe) => `My sensory recipe: ${recipe.situation}\n\nFirst choice: ${recipe.first || "Not chosen"}\nBackup: ${recipe.backup || "Not chosen"}\nAvoid: ${recipe.avoid || "Not chosen"}\nEarly signs: ${recipe.early.join(", ") || "Not chosen"}\nQuick step: ${recipe.quick || "Not set"}\nLonger step: ${recipe.longer || "Not set"}\n\nTest result: ${recipe.result || "Not recorded"}\nWhat I noticed: ${recipe.resultNote || "None"}`;

export function renderSensoryRecipe(root, tool) {
  const state = { page: "build" };
  let recipe = load();
  const chips = (items, selected, type) => items.map((item) => `<button type="button" class="recipe-chip ${selected.includes(item) ? "selected" : ""}" data-recipe-toggle="${type}" data-recipe-value="${attr(item)}">${esc(item)}</button>`).join("");
  const select = (label, field, options, placeholder) => `<label class="field recipe-mini-field"><span>${label}</span><select data-recipe-field="${field}"><option value="">${placeholder}</option>${options.map((item) => `<option value="${attr(item)}" ${recipe[field] === item ? "selected" : ""}>${esc(item)}</option>`).join("")}</select></label>`;
  const intro = (eyebrow, title, lead) => `<div class="recipe-intro recipe-intro-simple"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${lead}</p></div>`;
  const build = () => `${intro("Calm & sensory / A small plan", "Make one sensory recipe.", "Choose what is happening, pick what to try first, and keep a backup for when the first option is not possible. You do not need to fill everything in.")}<section class="recipe-workbench recipe-simple-workbench"><div class="recipe-progress"><span class="done">1</span><span>Situation</span><i></i><span class="active">2</span><span>First response</span><i></i><span>3</span><span>Recipe card</span></div><section class="recipe-simple-step"><p class="recipe-kicker">Step 1</p><h2>What kind of moment is this?</h2><p class="recipe-help">Pick the closest fit. It can be approximate.</p><div class="recipe-state-grid recipe-state-grid-simple">${situations.map((item) => `<button type="button" class="recipe-state ${recipe.situation === item ? "selected" : ""}" data-recipe-situation="${attr(item)}">${esc(item)}</button>`).join("")}</div></section><section class="recipe-simple-step"><p class="recipe-kicker">Step 2</p><h2>What could help first?</h2><p class="recipe-help">Choose one. You can add a backup later.</p><div class="recipe-support-grid">${supports.map((item) => `<button type="button" class="recipe-support ${recipe.first === item ? "selected" : ""}" data-recipe-first="${attr(item)}"><span>${recipe.first === item ? "✓" : "+"}</span>${esc(item)}</button>`).join("")}</div><div class="recipe-choice-line">${recipe.first ? `<strong>First choice:</strong> ${esc(recipe.first)}` : "Nothing chosen yet"}</div></section><details class="recipe-optional" ${recipe.backup || recipe.avoid || recipe.early.length ? "open" : ""}><summary>Optional: make the recipe more specific</summary><div class="recipe-optional-body"><p class="recipe-kicker">Early signs</p><p class="recipe-help">What tells you this recipe may be needed?</p><div class="recipe-chip-grid">${chips(earlySigns, recipe.early, "early")}</div><div class="recipe-detail-grid recipe-detail-grid-simple">${select("Backup if the first choice is unavailable", "backup", supports.filter((item) => item !== recipe.first), "Choose a backup")}${select("Something I usually avoid", "avoid", supports.filter((item) => item !== recipe.first), "Choose if useful")}</div><div class="recipe-detail-grid recipe-detail-grid-simple"><label class="field recipe-mini-field"><span>30-second version</span><input data-recipe-field="quick" value="${attr(recipe.quick)}" placeholder="The smallest useful step"></label><label class="field recipe-mini-field"><span>Longer version</span><input data-recipe-field="longer" value="${attr(recipe.longer)}" placeholder="If I have more time..."></label></div></div></details><div class="recipe-actions"><button type="button" class="button" data-recipe-action="summary">Show my recipe</button><button type="button" class="button secondary" data-recipe-action="clear">Start again</button></div></section>`;
  const summary = () => `${intro(`Your sensory recipe / ${recipe.situation}`, "A small plan for when it starts.", "Use the first choice if it is available. If not, use the backup or stop after the smallest useful step.")}<section class="recipe-card recipe-card-simple"><div class="recipe-card-title"><span>RECIPE</span><h2>${esc(recipe.situation)}</h2><button type="button" class="chip" data-recipe-action="build">Edit</button></div><div class="recipe-card-simple-main"><div class="recipe-card-lead"><span>TRY FIRST</span><strong>${esc(recipe.first || "Choose a first response")}</strong></div><div class="recipe-card-side"><p><b>Backup</b>${esc(recipe.backup || "None added")}</p><p><b>Avoid</b>${esc(recipe.avoid || "None added")}</p></div></div>${recipe.early.length ? `<div class="recipe-card-row"><b>Notice it when</b><span>${esc(recipe.early.join(" · "))}</span></div>` : ""}${(recipe.quick || recipe.longer) ? `<div class="recipe-card-row"><b>Time available</b><span>${recipe.quick ? `30 sec: ${esc(recipe.quick)}` : ""}${recipe.quick && recipe.longer ? " · " : ""}${recipe.longer ? `Longer: ${esc(recipe.longer)}` : ""}</span></div>` : ""}<section class="recipe-recheck recipe-recheck-simple"><h3>Try it once, then notice</h3><p>Did anything change? There is no right result; this just helps you learn what fits.</p><div class="recipe-chip-grid">${resultOptions.map((item) => `<button type="button" class="recipe-chip ${recipe.result === item ? "selected" : ""}" data-recipe-result="${attr(item)}">${esc(item)}</button>`).join("")}</div><label class="field"><span>One short note (optional)</span><textarea id="recipe-result-note" rows="2" placeholder="What I noticed...">${esc(recipe.resultNote)}</textarea></label></section><div class="recipe-actions"><button type="button" class="button" data-recipe-action="save-map">Save recipe</button><button type="button" class="button secondary" data-recipe-action="download">Download</button><button type="button" class="button secondary" data-recipe-action="copy">Copy</button></div><p id="recipe-status" class="fine" role="status"></p></section>`;
  const render = () => { root.innerHTML = `<div class="wrap sensory-recipe-page">${state.page === "build" ? build() : summary()}</div>`; bind(); };
  const bind = () => {
    root.querySelectorAll("[data-recipe-situation]").forEach((button) => button.addEventListener("click", () => { recipe.situation = button.dataset.recipeSituation; save(recipe); render(); }));
    root.querySelectorAll("[data-recipe-first]").forEach((button) => button.addEventListener("click", () => { recipe.first = recipe.first === button.dataset.recipeFirst ? "" : button.dataset.recipeFirst; save(recipe); render(); }));
    root.querySelectorAll("[data-recipe-toggle]").forEach((button) => button.addEventListener("click", () => { toggle(recipe.early, button.dataset.recipeValue); save(recipe); render(); }));
    root.querySelectorAll("[data-recipe-field]").forEach((input) => input.addEventListener("input", () => { recipe[input.dataset.recipeField] = input.value; save(recipe); }));
    root.querySelectorAll("[data-recipe-result]").forEach((button) => button.addEventListener("click", () => { recipe.result = button.dataset.recipeResult; save(recipe); render(); }));
    root.querySelector("#recipe-result-note")?.addEventListener("input", (event) => { recipe.resultNote = event.target.value; save(recipe); });
    root.querySelectorAll("[data-recipe-action]").forEach((button) => button.addEventListener("click", () => { const action = button.dataset.recipeAction; if (action === "summary") { state.page = "summary"; render(); } if (action === "build") { state.page = "build"; render(); } if (action === "clear") { recipe = empty(); save(recipe); render(); } if (action === "save-map") { try { const maps = JSON.parse(localStorage.getItem("ns-personal-maps-v1") || "[]"); maps.unshift({ id: crypto.randomUUID(), title: `Sensory recipe · ${recipe.situation}`, tool: "sensory-recipe", answers: recipe, savedAt: new Date().toISOString(), status: "New observation" }); localStorage.setItem("ns-personal-maps-v1", JSON.stringify(maps.slice(0, 250))); root.querySelector("#recipe-status").textContent = "Saved on this device."; } catch { root.querySelector("#recipe-status").textContent = "This browser could not save the recipe."; } } if (action === "download") download("sensory-recipe.txt", recipeText(recipe)); if (action === "copy") navigator.clipboard?.writeText(recipeText(recipe)).then(() => { root.querySelector("#recipe-status").textContent = "Copied."; }).catch(() => { root.querySelector("#recipe-status").textContent = "Copy was blocked. Use Download instead."; }); }));
  };
  render();
}
